// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthorizationPolicyRevision struct {
	OrganizationID pgtype.UUID
	Revision       int64
	UpdatedAt      pgtype.Timestamptz
}

type ContentBlock struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	BlockType      string
	CreatedBy      pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	RetiredAt      pgtype.Timestamptz
}

type ContentBlockPlacement struct {
	ID                 pgtype.UUID
	OrganizationID     pgtype.UUID
	ContainerVersionID pgtype.UUID
	BlockRevisionID    pgtype.UUID
	ParentPlacementID  pgtype.UUID
	Position           pgtype.Numeric
	RoleInParent       pgtype.Text
}

type ContentBlockRevision struct {
	ID                    pgtype.UUID
	OrganizationID        pgtype.UUID
	BlockID               pgtype.UUID
	RevisionNo            int64
	Content               string
	ContentFormat         string
	Props                 []byte
	OriginBlockRevisionID pgtype.UUID
	CreatedBy             pgtype.UUID
	CreatedAt             pgtype.Timestamptz
	ContentChecksum       string
}

type ContentContainer struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	WorkspaceID      pgtype.UUID
	Kind             string
	Title            string
	Status           string
	Visibility       string
	ParentID         pgtype.UUID
	SortKey          string
	CurrentVersionID pgtype.UUID
	CreatedBy        pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type ContentContainerVersion struct {
	ID              pgtype.UUID
	OrganizationID  pgtype.UUID
	ContainerID     pgtype.UUID
	VersionNo       int64
	CreatedBy       pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	ContentChecksum string
}

type ContentMemberPreference struct {
	UserID         pgtype.UUID
	OrganizationID pgtype.UUID
	Preferences    []byte
	UpdatedAt      pgtype.Timestamptz
}

type ContentModelingPlan struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	WorkspaceID    pgtype.UUID
	Intent         string
	TargetModelID  pgtype.UUID
	Sources        []byte
	Plan           []byte
	Status         string
	CreatedBy      pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type ContentWorkspace struct {
	ID                        pgtype.UUID
	OrganizationID            pgtype.UUID
	Slug                      string
	Name                      string
	Description               string
	Status                    string
	DefaultAgentApplicationID pgtype.UUID
	DefaultResourceModelID    pgtype.UUID
	Settings                  []byte
	Revision                  int64
	CreatedBy                 pgtype.UUID
	ArchivedAt                pgtype.Timestamptz
	ArchivedBy                pgtype.UUID
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

type ContentWorkspaceAgentApplication struct {
	ID                 pgtype.UUID
	OrganizationID     pgtype.UUID
	WorkspaceID        pgtype.UUID
	AgentApplicationID pgtype.UUID
	Enabled            bool
	CreatedBy          pgtype.UUID
	CreatedAt          pgtype.Timestamptz
}

type ContentWorkspaceInvitation struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	WorkspaceID    pgtype.UUID
	Email          string
	Role           string
	Status         string
	TokenHash      string
	InvitedBy      pgtype.UUID
	ExpiresAt      pgtype.Timestamptz
	AcceptedAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type ContentWorkspaceMember struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	WorkspaceID    pgtype.UUID
	UserID         pgtype.UUID
	Role           string
	GrantedBy      pgtype.UUID
	Revision       int64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type ContentWorkspaceSettingsRevision struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	WorkspaceID    pgtype.UUID
	Revision       int64
	Settings       []byte
	ChangedBy      pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type IdentityApiKey struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	KeyPrefix      string
	KeyHash        string
	Status         string
	ExpiresAt      pgtype.Timestamptz
	LastUsedAt     pgtype.Timestamptz
	Capabilities   []byte
	CreatedAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
}

type IdentityPasswordReset struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TokenHash  string
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type IdentitySession struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	TokenHash         string
	CreatedAt         pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	IpPrefix          pgtype.Text
	UserAgent         pgtype.Text
}

type IdentityUser struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	UserType         string
	Email            pgtype.Text
	DisplayName      string
	PasswordHash     pgtype.Text
	Status           string
	OrganizationRole pgtype.Text
	LastLoginAt      pgtype.Timestamptz
	Revision         int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type IdentityUserPreference struct {
	UserID                    pgtype.UUID
	DefaultWorkspaceID        pgtype.UUID
	Timezone                  string
	EmailNotificationsEnabled bool
	Revision                  int64
	UpdatedAt                 pgtype.Timestamptz
}

type NotificationEmailDelivery struct {
	ID                pgtype.UUID
	OrganizationID    pgtype.UUID
	Template          string
	RecipientEmail    string
	KeyVersion        int32
	EncryptedPayload  []byte
	Status            string
	AttemptCount      int32
	NextAttemptAt     pgtype.Timestamptz
	LockedBy          pgtype.Text
	LockedUntil       pgtype.Timestamptz
	SentAt            pgtype.Timestamptz
	ProviderMessageID pgtype.Text
	LastErrorCode     pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type OrganizationInvitationWorkspaceGrant struct {
	InvitationID   pgtype.UUID
	OrganizationID pgtype.UUID
	WorkspaceID    pgtype.UUID
	Role           string
}

type OrganizationMemberInvitation struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	Email            string
	DisplayName      pgtype.Text
	OrganizationRole string
	AuthorityScope   string
	ScopeWorkspaceID pgtype.UUID
	TokenHash        string
	Status           string
	ExpiresAt        pgtype.Timestamptz
	InvitedBy        pgtype.UUID
	AcceptedBy       pgtype.UUID
	AcceptedAt       pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	Revision         int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type OrganizationOrganization struct {
	ID        pgtype.UUID
	Slug      string
	Name      string
	Status    string
	Revision  int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type SecurityAuthRateLimit struct {
	BucketType      string
	KeyHash         string
	WindowStartedAt pgtype.Timestamptz
	AttemptCount    int32
	BlockedUntil    pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
