// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlan = `-- name: GetPlan :one
SELECT id::text, organization_id::text, workspace_id::text, intent,
    COALESCE(target_model_id::text, '') AS target_model_id, sources, plan, status,
    created_at, updated_at
FROM content.modeling_plans
WHERE organization_id = $1::uuid AND workspace_id = $2::uuid AND id = $3::uuid
`

type GetPlanParams struct {
	OrgID       pgtype.UUID
	WorkspaceID pgtype.UUID
	PlanID      pgtype.UUID
}

type GetPlanRow struct {
	ID             string
	OrganizationID string
	WorkspaceID    string
	Intent         string
	TargetModelID  interface{}
	Sources        []byte
	Plan           []byte
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetPlan(ctx context.Context, arg GetPlanParams) (GetPlanRow, error) {
	row := q.db.QueryRow(ctx, getPlan, arg.OrgID, arg.WorkspaceID, arg.PlanID)
	var i GetPlanRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.Intent,
		&i.TargetModelID,
		&i.Sources,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPlan = `-- name: InsertPlan :one

INSERT INTO content.modeling_plans
    (organization_id, workspace_id, intent, target_model_id, sources, plan, status, created_by)
VALUES ($1::uuid, $2::uuid, $3, $4::uuid,
        $5::jsonb, $6::jsonb, 'draft', $7::uuid)
RETURNING id::text, organization_id::text, workspace_id::text, intent,
    COALESCE(target_model_id::text, '') AS target_model_id, sources, plan, status,
    created_at, updated_at
`

type InsertPlanParams struct {
	OrgID         pgtype.UUID
	WorkspaceID   pgtype.UUID
	Intent        string
	TargetModelID pgtype.UUID
	Sources       []byte
	Plan          []byte
	CreatedBy     pgtype.UUID
}

type InsertPlanRow struct {
	ID             string
	OrganizationID string
	WorkspaceID    string
	Intent         string
	TargetModelID  interface{}
	Sources        []byte
	Plan           []byte
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// 建模计划域查询（sqlc 契约文件）：internal/modeling 服务的全部数据访问。
// 运行环境为已 set_config('app.organization_id', <org>, true) 的事务
// （RLS 试点 0045），此处 SQL 只做业务过滤。
func (q *Queries) InsertPlan(ctx context.Context, arg InsertPlanParams) (InsertPlanRow, error) {
	row := q.db.QueryRow(ctx, insertPlan,
		arg.OrgID,
		arg.WorkspaceID,
		arg.Intent,
		arg.TargetModelID,
		arg.Sources,
		arg.Plan,
		arg.CreatedBy,
	)
	var i InsertPlanRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.Intent,
		&i.TargetModelID,
		&i.Sources,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT id::text, organization_id::text, workspace_id::text, intent,
    COALESCE(target_model_id::text, '') AS target_model_id, sources, plan, status,
    created_at, updated_at
FROM content.modeling_plans
WHERE organization_id = $1::uuid AND workspace_id = $2::uuid
ORDER BY created_at DESC
LIMIT $3::int
`

type ListPlansParams struct {
	OrgID       pgtype.UUID
	WorkspaceID pgtype.UUID
	RowLimit    int32
}

type ListPlansRow struct {
	ID             string
	OrganizationID string
	WorkspaceID    string
	Intent         string
	TargetModelID  interface{}
	Sources        []byte
	Plan           []byte
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListPlans(ctx context.Context, arg ListPlansParams) ([]ListPlansRow, error) {
	rows, err := q.db.Query(ctx, listPlans, arg.OrgID, arg.WorkspaceID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlansRow
	for rows.Next() {
		var i ListPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WorkspaceID,
			&i.Intent,
			&i.TargetModelID,
			&i.Sources,
			&i.Plan,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPlan = `-- name: LockPlan :one
SELECT id::text, organization_id::text, workspace_id::text, intent,
    COALESCE(target_model_id::text, '') AS target_model_id, sources, plan, status,
    created_at, updated_at
FROM content.modeling_plans
WHERE organization_id = $1::uuid AND workspace_id = $2::uuid AND id = $3::uuid
FOR UPDATE
`

type LockPlanParams struct {
	OrgID       pgtype.UUID
	WorkspaceID pgtype.UUID
	PlanID      pgtype.UUID
}

type LockPlanRow struct {
	ID             string
	OrganizationID string
	WorkspaceID    string
	Intent         string
	TargetModelID  interface{}
	Sources        []byte
	Plan           []byte
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) LockPlan(ctx context.Context, arg LockPlanParams) (LockPlanRow, error) {
	row := q.db.QueryRow(ctx, lockPlan, arg.OrgID, arg.WorkspaceID, arg.PlanID)
	var i LockPlanRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.Intent,
		&i.TargetModelID,
		&i.Sources,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlanBody = `-- name: UpdatePlanBody :exec
UPDATE content.modeling_plans SET plan = $1::jsonb, updated_at = now()
WHERE organization_id = $2::uuid AND workspace_id = $3::uuid AND id = $4::uuid
`

type UpdatePlanBodyParams struct {
	Plan        []byte
	OrgID       pgtype.UUID
	WorkspaceID pgtype.UUID
	PlanID      pgtype.UUID
}

func (q *Queries) UpdatePlanBody(ctx context.Context, arg UpdatePlanBodyParams) error {
	_, err := q.db.Exec(ctx, updatePlanBody,
		arg.Plan,
		arg.OrgID,
		arg.WorkspaceID,
		arg.PlanID,
	)
	return err
}

const updatePlanStatus = `-- name: UpdatePlanStatus :one
UPDATE content.modeling_plans SET status = $1, updated_at = now()
WHERE organization_id = $2::uuid AND workspace_id = $3::uuid AND id = $4::uuid
RETURNING id::text, organization_id::text, workspace_id::text, intent,
    COALESCE(target_model_id::text, '') AS target_model_id, sources, plan, status,
    created_at, updated_at
`

type UpdatePlanStatusParams struct {
	Status      string
	OrgID       pgtype.UUID
	WorkspaceID pgtype.UUID
	PlanID      pgtype.UUID
}

type UpdatePlanStatusRow struct {
	ID             string
	OrganizationID string
	WorkspaceID    string
	Intent         string
	TargetModelID  interface{}
	Sources        []byte
	Plan           []byte
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpdatePlanStatus(ctx context.Context, arg UpdatePlanStatusParams) (UpdatePlanStatusRow, error) {
	row := q.db.QueryRow(ctx, updatePlanStatus,
		arg.Status,
		arg.OrgID,
		arg.WorkspaceID,
		arg.PlanID,
	)
	var i UpdatePlanStatusRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.Intent,
		&i.TargetModelID,
		&i.Sources,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
