// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"context"
)

type Querier interface {
	GetPlan(ctx context.Context, arg GetPlanParams) (GetPlanRow, error)
	// 建模计划域查询（sqlc 契约文件）：internal/modeling 服务的全部数据访问。
	// 运行环境为已 set_config('app.organization_id', <org>, true) 的事务
	// （RLS 试点 0045），此处 SQL 只做业务过滤。
	InsertPlan(ctx context.Context, arg InsertPlanParams) (InsertPlanRow, error)
	ListPlans(ctx context.Context, arg ListPlansParams) ([]ListPlansRow, error)
	LockPlan(ctx context.Context, arg LockPlanParams) (LockPlanRow, error)
	UpdatePlanBody(ctx context.Context, arg UpdatePlanBodyParams) error
	UpdatePlanStatus(ctx context.Context, arg UpdatePlanStatusParams) (UpdatePlanStatusRow, error)
}

var _ Querier = (*Queries)(nil)
